title: Ghostlyrar
url: ""
baseurl: ""

# Add your profile picture
profile_pic: "./images/rar.png" 

tracking_id: #

footer: yes
footer_url: "https://github.com/0xRar"
footer_text: "Ghostlyrar By 0xRar"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: "/"
 - name: "Contact"
   link: "/contact"
 - name: "Blog"
   link: "/blog"

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  syntax_highlighter: rouge
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
  
  # Line Numbers
  syntax_highlighter_opts:
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

