title: Ghostlyrar
url: ""
baseurl: ""

# Add your profile picture
profile_pic: "./images/rar.png" 

tracking_id: #

footer: yes
footer_url: ""
footer_text: "By 0xRar, An edit of the theme researcher"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: "/"
 - name: "Contact"
   link: "contact"
 - name: "Blog"
   link: "blog"


# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false


# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
